// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/tg_reaction/internal/use_case (interfaces: CryLoudReactionUseCase)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/use_case/mock_cry_loud_reaction_use_case.go -package=use_case_mocks github.com/fromsi/tg_reaction/internal/use_case CryLoudReactionUseCase
//

// Package use_case_mocks is a generated GoMock package.
package use_case_mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCryLoudReactionUseCase is a mock of CryLoudReactionUseCase interface.
type MockCryLoudReactionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCryLoudReactionUseCaseMockRecorder
	isgomock struct{}
}

// MockCryLoudReactionUseCaseMockRecorder is the mock recorder for MockCryLoudReactionUseCase.
type MockCryLoudReactionUseCaseMockRecorder struct {
	mock *MockCryLoudReactionUseCase
}

// NewMockCryLoudReactionUseCase creates a new mock instance.
func NewMockCryLoudReactionUseCase(ctrl *gomock.Controller) *MockCryLoudReactionUseCase {
	mock := &MockCryLoudReactionUseCase{ctrl: ctrl}
	mock.recorder = &MockCryLoudReactionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCryLoudReactionUseCase) EXPECT() *MockCryLoudReactionUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCryLoudReactionUseCase) Execute(chatId int64, messageId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", chatId, messageId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockCryLoudReactionUseCaseMockRecorder) Execute(chatId, messageId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCryLoudReactionUseCase)(nil).Execute), chatId, messageId)
}
