// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/tg_reaction/internal/use_case (interfaces: PoopReactionUseCase)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/use_case/mock_poop_reaction.go -package=use_case_mocks github.com/fromsi/tg_reaction/internal/use_case PoopReactionUseCase
//

// Package use_case_mocks is a generated GoMock package.
package use_case_mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPoopReactionUseCase is a mock of PoopReactionUseCase interface.
type MockPoopReactionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPoopReactionUseCaseMockRecorder
	isgomock struct{}
}

// MockPoopReactionUseCaseMockRecorder is the mock recorder for MockPoopReactionUseCase.
type MockPoopReactionUseCaseMockRecorder struct {
	mock *MockPoopReactionUseCase
}

// NewMockPoopReactionUseCase creates a new mock instance.
func NewMockPoopReactionUseCase(ctrl *gomock.Controller) *MockPoopReactionUseCase {
	mock := &MockPoopReactionUseCase{ctrl: ctrl}
	mock.recorder = &MockPoopReactionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoopReactionUseCase) EXPECT() *MockPoopReactionUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockPoopReactionUseCase) Execute(chatId int64, messageId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", chatId, messageId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockPoopReactionUseCaseMockRecorder) Execute(chatId, messageId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockPoopReactionUseCase)(nil).Execute), chatId, messageId)
}
