include:
  - project: 'devops/specs/gitlab-ci'
    ref: master
    file: '/templates/k3s-deploy-go/template.yaml'

workflow:
  rules:
    # коммит в master
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
  HARBOR_LIBRARY: ${HARBOR_HOST}/library
  HARBOR_IMAGE: ${HARBOR_HOST}/${CI_PROJECT_PATH}

stages:
  - test
  - lint
  - build
  - deploy

test:
  image: golang:1.24
  stage: test
  script:
    - go test -v -coverpkg=./internal/...,./pkg/... ./...

lint:
  image: golangci/golangci-lint:v1.64
  stage: lint
  script:
    - golangci-lint run -v

build_image:
  image: docker:20.10.16
  stage: build
  before_script:
    - docker login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD $HARBOR_HOST
  script:
    - docker build . -t ${HARBOR_IMAGE}/app:${CI_COMMIT_SHA}
    - docker push ${HARBOR_IMAGE}/app:${CI_COMMIT_SHA}
  after_script:
    - docker logout $HARBOR_HOST

deploy_production:
  stage: deploy
  extends: .deploy_k3s
  when: manual
  variables:
    ENVIRONMENT: production
    KUBECONFIG: ${KUBECONFIG_INFRA}
  environment:
    name: production
  rules:
    - when: manual
      allow_failure: true
