// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/tg_reaction/internal/services (interfaces: TelebotMethodService)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/services/mock_telebot_method.go -package=services_mocks github.com/fromsi/tg_reaction/internal/services TelebotMethodService
//

// Package services_mocks is a generated GoMock package.
package services_mocks

import (
	reflect "reflect"

	json "github.com/fromsi/tg_reaction/pkg/json"
	gomock "go.uber.org/mock/gomock"
)

// MockTelebotMethodService is a mock of TelebotMethodService interface.
type MockTelebotMethodService struct {
	ctrl     *gomock.Controller
	recorder *MockTelebotMethodServiceMockRecorder
	isgomock struct{}
}

// MockTelebotMethodServiceMockRecorder is the mock recorder for MockTelebotMethodService.
type MockTelebotMethodServiceMockRecorder struct {
	mock *MockTelebotMethodService
}

// NewMockTelebotMethodService creates a new mock instance.
func NewMockTelebotMethodService(ctrl *gomock.Controller) *MockTelebotMethodService {
	mock := &MockTelebotMethodService{ctrl: ctrl}
	mock.recorder = &MockTelebotMethodServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelebotMethodService) EXPECT() *MockTelebotMethodServiceMockRecorder {
	return m.recorder
}

// SetMessageReaction mocks base method.
func (m *MockTelebotMethodService) SetMessageReaction(chatId int64, messageId int, reaction json.Reaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMessageReaction", chatId, messageId, reaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMessageReaction indicates an expected call of SetMessageReaction.
func (mr *MockTelebotMethodServiceMockRecorder) SetMessageReaction(chatId, messageId, reaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMessageReaction", reflect.TypeOf((*MockTelebotMethodService)(nil).SetMessageReaction), chatId, messageId, reaction)
}
