// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/tg_reaction/internal/services (interfaces: QueryTelebotMethodService)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/services/mock_query_telebot_method.go -package=services_mocks github.com/fromsi/tg_reaction/internal/services QueryTelebotMethodService
//

// Package services_mocks is a generated GoMock package.
package services_mocks

import (
	gomock "go.uber.org/mock/gomock"
)

// MockQueryTelebotMethodService is a mock of QueryTelebotMethodService interface.
type MockQueryTelebotMethodService struct {
	ctrl     *gomock.Controller
	recorder *MockQueryTelebotMethodServiceMockRecorder
	isgomock struct{}
}

// MockQueryTelebotMethodServiceMockRecorder is the mock recorder for MockQueryTelebotMethodService.
type MockQueryTelebotMethodServiceMockRecorder struct {
	mock *MockQueryTelebotMethodService
}

// NewMockQueryTelebotMethodService creates a new mock instance.
func NewMockQueryTelebotMethodService(ctrl *gomock.Controller) *MockQueryTelebotMethodService {
	mock := &MockQueryTelebotMethodService{ctrl: ctrl}
	mock.recorder = &MockQueryTelebotMethodServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryTelebotMethodService) EXPECT() *MockQueryTelebotMethodServiceMockRecorder {
	return m.recorder
}
