// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/tg_reaction/internal/configs (interfaces: Config)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/configs/mock_config.go -package=configs_mocks github.com/fromsi/tg_reaction/internal/configs Config
//

// Package configs_mocks is a generated GoMock package.
package configs_mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockConfig is a mock of Config interface.
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMockRecorder
	isgomock struct{}
}

// MockConfigMockRecorder is the mock recorder for MockConfig.
type MockConfigMockRecorder struct {
	mock *MockConfig
}

// NewMockConfig creates a new mock instance.
func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
	mock := &MockConfig{ctrl: ctrl}
	mock.recorder = &MockConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfig) EXPECT() *MockConfigMockRecorder {
	return m.recorder
}

// GetTelegramToken mocks base method.
func (m *MockConfig) GetTelegramToken() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTelegramToken")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTelegramToken indicates an expected call of GetTelegramToken.
func (mr *MockConfigMockRecorder) GetTelegramToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTelegramToken", reflect.TypeOf((*MockConfig)(nil).GetTelegramToken))
}
